# Generated by Django 4.2.27 on 2026-01-14 02:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0003_mealplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("would_repeat", models.BooleanField()),
                ("comment", models.TextField(blank=True, default="")),
                ("rated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="meals.mealplan",
                    ),
                ),
            ],
        ),
    ]
