# Generated by Django 4.2.27 on 2026-01-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0004_mealrating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.DeleteModel(
            name="Meal",
        ),
    ]
