# Generated by Django 4.2.27 on 2026-01-29 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0005_delete_ingredient_delete_meal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "main_recipe",
                    models.ForeignKey(
                        limit_choices_to={"kind": "MAIN"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combos_as_main",
                        to="meals.recipe",
                    ),
                ),
                (
                    "side_recipe",
                    models.ForeignKey(
                        limit_choices_to={"kind": "SIDE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combos_as_side",
                        to="meals.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["main_recipe__name", "side_recipe__name"],
                "unique_together": {("main_recipe", "side_recipe")},
            },
        ),
    ]
