# Generated by Django 4.2.27 on 2026-01-29 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0006_combo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComboStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("times_made", models.PositiveIntegerField(default=0)),
                ("avg_rating", models.FloatField(default=0.0)),
                ("would_repeat_rate", models.FloatField(default=0.0)),
                ("last_made_at", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "combo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="meals.combo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "combo stats",
            },
        ),
    ]
