# Generated by Django 4.2.27 on 2026-01-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0007_combostats"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
