# Generated by Django 4.2.27 on 2026-01-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="color_hex",
            field=models.CharField(default="#6B7280", max_length=7),
        ),
    ]
