# Generated by Django 4.2.27 on 2026-01-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_domain_color_hex"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="color_hex",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="assigned_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="completion_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
