# Generated by Django 4.2.27 on 2026-01-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_project_color_hex_task_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskschedulerule",
            name="timezone",
            field=models.CharField(default="America/New_York", max_length=63),
        ),
    ]
