# Generated by Django 4.2.27 on 2026-01-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_taskschedulerule_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinstance",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="skipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
