# Generated by Django 4.2.27 on 2026-01-31 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_taskinstance_completed_at_taskinstance_skipped_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tasks.domain",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tasks.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("domain__isnull", True), ("project__isnull", False)),
                    models.Q(("domain__isnull", False), ("project__isnull", True)),
                    _connector="OR",
                ),
                name="task_project_xor_domain",
            ),
        ),
    ]
