# Generated by Django 4.2.27 on 2026-01-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_task_domain_alter_task_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskschedulerule",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
