# Generated by Django 4.2.27 on 2026-01-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_schedule_rule_is_active"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "is_active"],
                name="tasks_task_assigne_fc2d84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskinstance",
            index=models.Index(
                fields=["instance_date", "completion_order"],
                name="tasks_taski_instanc_9879f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskinstance",
            index=models.Index(
                fields=["instance_date", "source"],
                name="tasks_taski_instanc_721691_idx",
            ),
        ),
    ]
