# Generated by Django 4.2.27 on 2026-01-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_analytics_indexes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="taskinstance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completion_order__isnull", False)),
                fields=("instance_date", "completion_order"),
                name="unique_completion_order_per_date",
            ),
        ),
    ]
